namespace Events
{
    public enum BhanuEvent
    {
        ConnectedToInternetEvent,
        ConnectedToMasterEvent,
        ConnectingToMasterEvent,
        CreateRoomFailedEvent,
        CreateRoomRequestEvent,
        ElectricBoxCollidedEvent,
        ElectricBoxNotCollidedEvent,
        FindRoomEvent,
        FindingRoomEvent,
        JoinedLobbyEvent,
        JoinedRoomEvent,
        LeaveRoomRequestEvent,
        LeavingRoomEvent,
        LeavingRoomFailedEvent,
        LeftRoomEvent,
        NoInternetEvent,
        RoomsListUpdatedEvent,
        StartCutsceneFinishedEvent,
        StartCutsceneStartedEvent,
        TryAgainEvent,
        WinCutsceneFinishedEvent,
        WinCutsceneStartedEvent,
        WinEvent
    }
}
